### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Lemonszz** [Lemonszz/LKLib#1]
- [ ] Brewing Fuel API
- [ ] Hoe Dirt->Tilled API
- [ ] Lake Blocker API
- [ ] LandPathNode API
- [ ] PlantBlock CanPlantOnBlock (tag?)
- [ ] EntityPart API
- [ ] DirectionalData Block & Handler
- [ ] Spawn Restriction API
- [ ] Villager Danger API
- [ ] FakeItem API (automatically hide in REI?)
- [ ] Creative Sub tab customisation
- [x] Note Block Instrument
